import Head from "next/head";
import Sidebar from "../components/sidebar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Blogie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full flex-col lg:flex-row">
        <Sidebar />
        <div className="flex lg:ml-72 xl:ml-80 lg:p-8 w-full"></div>
      </main>
    </div>
  );
}
